########################### SERVICES
services:
  mealie-backup-ts:
    container_name: "mealie-backup-ts"
    image: tailscale/tailscale:latest
    hostname: mealie-backup
    environment:
      - TS_EXTRA_ARGS=--advertise-tags=tag:container --auth-key file:/run/secrets/TS_AUTHKEY_MEALIE_BACKUP
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ACCEPT_DNS=true  
    volumes:
      - $WORKINGDIR/docker/ts/mealie-backup/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    secrets:
      - TS_AUTHKEY_MEALIE_BACKUP
    healthcheck:
      test: ["CMD", "tailscale", "status", "--json"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mealie-backup:
    container_name: mealie-backup
    build: .
    volumes:
      - $WORKINGDIR/docker/mealie-backup/app:/app
    command: ["python", "/app/mealie-backup.py"]
    network_mode: "service:mealie-backup-ts"
    depends_on:
      mealie-backup-ts:
        condition: service_healthy
    secrets:
      - MEALIE_BASE_URL
      - MEALIE_BASE_URL_TS
      - MEALIE_BACKUP_ENDPOINT
      - MEALIE_AUTH_TOKEN

secrets:
  MEALIE_BASE_URL:
    file: ./secrets/MEALIE_BASE_URL
  MEALIE_BASE_URL_TS:
    file: ./secrets/MEALIE_BASE_URL_TS
  MEALIE_BACKUP_ENDPOINT:
    file: ./secrets/MEALIE_BACKUP_ENDPOINT
  MEALIE_AUTH_TOKEN:
    file: ./secrets/MEALIE_AUTH_TOKEN
  TS_AUTHKEY_MEALIE_BACKUP:
    file: ./secrets/TS_AUTHKEY_MEALIE_BACKUP
