########################### SERVICES
services:
  mealie-backup-ts:
    container_name: "mealie-backup-ts"
    image: tailscale/tailscale:latest
    hostname: mealie-backup
    environment:
      - TS_AUTHKEY=$TS_AUTHKEY_MEALIE
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ACCEPT_DNS=true  
    volumes:
      - $WORKINGDIR/docker/ts/mealie-backup/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module

  mealie-backup:
    container_name: mealie-backup
    build: .
    environment:
      - BASE_URL=$MEALIE_BASE_URL
      - ENDPOINT=$MEALIE_ENDPOINT
      - AUTH_TOKEN=$MEALIE_AUTH_TOKEN
    volumes:
      - $WORKINGDIR/docker/mealie-backup/app:/app
    command: ["python", "/app/mealie-backup.py"]
    network_mode: "service:mealie-backup-ts"
    depends_on:
      - mealie-backup-ts